export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_LOGIN = "REGISTER_LOGIN"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_RESET = "LOGIN_RESET"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"
export const LOGOUT_RESET = "LOGOUT_RESET"


export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"

export const ACCESS_CHAT_REQUEST = "ACCESS_CHAT_REQUEST"
export const ACCESS_CHAT_SUCCESS = "ACCESS_CHAT_SUCCESS"
export const ACCESS_CHAT_FAIL = "ACCESS_CHAT_FAIL"

export const ALL_CHATS_OF_USER_REQUEST = "ALL_CHATS_OF_USER_REQUEST"
export const ALL_CHATS_OF_USER_SUCCESS = "ALL_CHATS_OF_USER_SUCCESS"
export const ALL_CHATS_OF_USER_FAIL = "ALL_CHATS_OF_USER_FAIL"