export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_LOGIN = "REGISTER_LOGIN"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_RESET = "LOGIN_RESET"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"
export const LOGOUT_RESET = "LOGOUT_RESET"


export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"
export const SEARCH_USER_RESET = "SEARCH_USER_RESET"

export const ACCESS_CHAT_REQUEST = "ACCESS_CHAT_REQUEST"
export const ACCESS_CHAT_SUCCESS = "ACCESS_CHAT_SUCCESS"
export const ACCESS_CHAT_FAIL = "ACCESS_CHAT_FAIL"

export const ALL_CHATS_OF_USER_REQUEST = "ALL_CHATS_OF_USER_REQUEST"
export const ALL_CHATS_OF_USER_SUCCESS = "ALL_CHATS_OF_USER_SUCCESS"
export const ALL_CHATS_OF_USER_FAIL = "ALL_CHATS_OF_USER_FAIL"


export const CREATE_A_GROUP_CHAT_REQUEST = "CREATE_A_GROUP_CHAT_REQUEST"
export const CREATE_A_GROUP_CHAT_SUCCESS = "CREATE_A_GROUP_CHAT_SUCCESS"
export const CREATE_A_GROUP_CHAT_FAIL = "CREATE_A_GROUP_CHAT_FAIL"
export const CREATE_A_GROUP_CHAT_RESET = "CREATE_A_GROUP_CHAT_RESET"


export const RENAME_CHAT_REQUEST = "RENAME_CHAT_REQUEST"
export const RENAME_CHAT_SUCCESS = "RENAME_CHAT_SUCCESS"
export const RENAME_CHAT_FAIL = "RENAME_CHAT_FAIL"
export const RENAME_CHAT_RESET = "RENAME_CHAT_RESET"


export const ADD_USER_TO_GROUP_REQUEST = "ADD_USER_TO_GROUP_REQUEST"
export const ADD_USER_TO_GROUP_SUCCESS = "ADD_USER_TO_GROUP_SUCCESS"
export const ADD_USER_TO_GROUP_FAIL = "ADD_USER_TO_GROUP_FAIL"
export const ADD_USER_TO_GROUP_RESET = "ADD_USER_TO_GROUP_RESET"

export const DELETE_FROM_GROUP_REQUEST = "DELETE_FROM_GROUP_REQUEST"
export const DELETE_FROM_GROUP_SUCCESS = "DELETE_FROM_GROUP_SUCCESS"
export const DELETE_FROM_GROUP_FAIL = "DELETE_FROM_GROUP_FAIL"
export const DELETE_FROM_GROUP_RESET = "DELETE_FROM_GROUP_RESET"

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL"
export const SEND_MESSAGE_RESET = "SEND_MESSAGE_RESET"

export const ALL_MESSAGES_REQUEST = "ALL_MESSAGES_REQUEST"
export const ALL_MESSAGES_SUCCESS = "ALL_MESSAGES_SUCCESS"
export const ALL_MESSAGES_FAIL = "ALL_MESSAGES_FAIL"
export const ALL_MESSAGES_RESET = "ALL_MESSAGES_RESET"

export const SEARCH_A_GROUP_REQUEST = "SEARCH_A_GROUP_REQUEST"
export const SEARCH_A_GROUP_SUCCESS = "SEARCH_A_GROUP_SUCCESS"
export const SEARCH_A_GROUP_FAIL = "SEARCH_A_GROUP_FAIL"
export const SEARCH_A_GROUP_RESET = "SEARCH_A_GROUP_RESET"


export const JOIN_A_GROUP_REQUEST = "JOIN_A_GROUP_REQUEST"
export const JOIN_A_GROUP_SUCCESS = "JOIN_A_GROUP_SUCCESS"
export const JOIN_A_GROUP_FAIL = "JOIN_A_GROUP_FAIL"


export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST"
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS"
export const ALL_USERS_FAIL = "ALL_USERS_FAIL"


export const GET_ALL_PUBLIC_CHAT_USER_REQUEST = "GET_ALL_PUBLIC_CHAT_USER_REQUEST"
export const GET_ALL_PUBLIC_CHAT_USER_SUCCESS = "GET_ALL_PUBLIC_CHAT_USER_SUCCESS"
export const GET_ALL_PUBLIC_CHAT_USER_FAIL = "GET_ALL_PUBLIC_CHAT_USER_FAIL"
